[theme]
base = "light"
primaryColor = "#23566D"
backgroundColor = "#F5F8FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#152F40"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200
enableXsrfProtection = true

[browser]
gatherUsageStats = false
